/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.apache.lucene:lucene-core:8.9.0")
    implementation("org.apache.lucene:lucene-queries:8.9.0")
    implementation("org.apache.lucene:lucene-test-framework:8.9.0")
    implementation("org.apache.lucene:lucene-analyzers-common:8.9.0")
    implementation("org.apache.lucene:lucene-queryparser:8.9.0")
    implementation("org.projectlombok:lombok:RELEASE")
    implementation("org.apache.logging.log4j:log4j-core:2.14.1")
    implementation("com.jakewharton.picnic:picnic:0.5.0")
}

group = "org.lucene.visualize"
version = "1.0.0"
description = "visualize-lucene"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
